
services:
  postgres:
    image: postgres:16-alpine
    container_name: centre-sportif-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5462:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U player_pyke -d centredb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

